### ISSUE TITLE
A question about the evaluation code

### ISSUE THREAD

**Issue by air-tea** [TUDB-Labs/MoE-PEFT#10]
Thanks for your excellent work!

I have a question about the evaluation code. The evaluation code extracts the last token in the generated answer of the LLM and uses it to compare it with the ground truth label. Is this setting a comment setting in the evaluation of tasks such as single-label classification? What if the generated answer has the label in the middle of it?

**Comment by mikecovlee** [comment]
Sorry it took so long to see this. The method we used is commonly used in common sense tasks.

**Comment by air-tea** [comment]
I get it, thanks for your reply.
