### ISSUE TITLE
MoE-Peft使用MoLA与LoRAMoE为路由策略时Evaluate部分出现如下问题，使用MixLoRA时无此问题

### ISSUE THREAD

**Issue by ShanRom** [TUDB-Labs/MoE-PEFT#14]
![QQ图片20241204191910](https://github.com/user-attachments/assets/eccb4e0c-23b9-458c-8659-cd7054cb74b3)
训练过程无问题，仅在MoLA及LoRAMoE的评估部分出错
相关配置如下：
CUDA_VISIBLE_DEVICES=3 python moe_peft.py \
  --base_model meta-llama/Llama-2-7b-hf \
  --config moe_peft_loramoe.json \
  --log_file moe_peft_loramoe.log \
  --bf16 \
  --evaluate

CUDA_VISIBLE_DEVICES=4 python moe_peft.py \
  --base_model meta-llama/Llama-2-7b-hf \
  --config moe_peft_mola.json \
  --log_file moe_peft_mola.log \
  --bf16 \
  --evaluate

**Comment by mikecovlee** [comment]
thx. i will check it in latest pr.

**Comment by mikecovlee** [comment]
方便看下config吗？我这边没办法复现

**Comment by ShanRom** [comment]
配置生成：
python launch.py gen \
  --template loramoe \
  --tasks 'arc-e;arc-c;boolq;obqa' \
  --file_name 'moe_peft_loramoe.json' \
  --multi_task True
模型训练：
python moe_peft.py \
  --base_model meta-llama/Llama-2-7b-hf \
  --config moe_peft_loramoe.json \
  --log_file moe_peft_loramoe.log \
  --bf16
评估（出现bug）：
python moe_peft.py \
  --base_model meta-llama/Llama-2-7b-hf \
  --config moe_peft_loramoe.json \
  --log_file moe_peft_loramoe.log \
  --bf16 \
  --evaluate
再次感谢您的回复！

**Comment by mikecovlee** [comment]
补丁已推送，请问是否方便进行测试？十分感谢

**Comment by ShanRom** [comment]
抱歉，还是出现此问题，本次测试时使用1小时前您推送的moe_peft.py对原始版本进行覆盖。还是说我仍遗漏了您推送的部分修改？

**Comment by mikecovlee** [comment]
请使用 https://github.com/TUDB-Labs/MoE-PEFT/pull/20 的分支进行测试，你这边测试通过后我才会合并该PR

**Comment by ShanRom** [comment]
感谢您的耐心解答，mola和loramoe的bug现在均已修复。祝您科研顺利，生活愉快。
