### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by loadingyy** [TUDB-Labs/MoE-PEFT#16]
When set the "cutoff_len" in the config to "-1",  there will be an attributeError in moe_peft.py line 148. 
AttributeError: 'LLMModel' object has no attribute 'max_seq_len_'
The max_seq_len_ is in llm_model.config_.max_seq_len, not in llm_model.max_seq_len_.
Don't forget to fix line 149, too.

**Comment by mikecovlee** [comment]
thx. i will check it in latest pr.
